# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy PHP app to Azure Web App - pilotspanbackend

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read # Required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # Upgraded PHP version

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      - name: Install dependencies if composer.json exists
        if: steps.check_files.outputs.exists == 'true'
        run: |
          composer validate --no-check-publish
          composer install --no-dev --prefer-dist --no-progress
          composer dump-autoload --optimize

      - name: Verify vendor directory
        run: |
          if [ ! -d "vendor" ]; then
            echo "Error: vendor directory is missing! Composer install may have failed."
            exit 1
          fi

      - name: Optimize Laravel
        run: |
          php artisan cache:clear
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
        working-directory: ${{ github.workspace }}

      - name: Set permissions
        run: chmod -R 775 storage bootstrap/cache

      - name: Zip artifact for deployment
        run: zip -r release.zip . -x "*/.git/*" "*/node_modules/*" "storage/logs/*" ".env" "tests/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip -d ${{ runner.temp }}/deployment
          shopt -s dotglob
          mv ${{ runner.temp }}/deployment/* .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'pilotspanbackend'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
