# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy PHP app to Azure Web App - pilotspanbackend

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read # Required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'  # Upgraded PHP version

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      - name: Install dependencies if composer.json exists
        if: steps.check_files.outputs.exists == 'true'
        run: |
          composer validate --no-check-publish
          composer clear-cache  # Clear composer cache to prevent corruption
          composer install --no-dev --prefer-dist --no-progress
          composer dump-autoload --optimize

      - name: Set correct file permissions
        run: chmod -R 755 .

      - name: Zip artifact for deployment
        run: zip -r release.zip . -x "*.git*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Install unzip (if missing)
        run: sudo apt-get install -y unzip

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip -d ${{ runner.temp }}/deployment
          echo "Checking deployment directory contents..."
          ls -la ${{ runner.temp }}/deployment

      - name: Move extracted files to workspace
        run: |
          echo "Moving extracted files..."
          rsync -av ${{ runner.temp }}/deployment/ . 
          find ${{ runner.temp }}/deployment -type f -delete  # Ensure cleanup
          rm -rf ${{ runner.temp }}/deployment
          ls -la  # Verify files were moved

      - name: Ensure vendor dependencies are installed
        run: |
          if [ ! -f "/home/site/wwwroot/vendor/autoload.php" ]; then
            echo "vendor/autoload.php missing. Running composer install..."
            composer install --no-dev --prefer-dist --no-progress
            composer dump-autoload --optimize
          else
            echo "vendor/autoload.php found. Skipping composer install."
          fi

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy
        with:
          app-name: 'pilotspanbackend'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

      - name: Verify deployment success
        run: echo "Deployment completed successfully. Check Azure Portal for status."
